spring.application.name=backend

# Base de datos
spring.datasource.url=jdbc:postgresql://dpg-d7ns2orbc2fs7391ih00-a.ohio-postgres.render.com/mydb_kgj2?sslmode=require&currentSchema=public
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

# Puerto
server.port=8080
